markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
encoding: utf-8

google_analytics_id: UA-63569270-1

bbs_url: https://bbs.fcgvisa.com
help_url:

collections:
  docs:
    output: true

name: 关于飞出国（flyabroad.me）
description: 关于飞出国，关于 flyabroad ，飞出国怎么样
url: https://flyabroad.me

gems:
  - jekyll-feed
